version: "3.1"

services:
    db:
        image: postgres
        volumes:
            - db-storage:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=example
        # ports:
        #     - "5432:5432"
        restart: always
        networks:
            - backend
            - traefik-net

    scraper:
        build: ./scraper
        volumes:
            - iracing-notify-store:/app/data/
            - ./scraper/scraper/:/app/scraper/
        restart: always
        environment:
            - API_URL=http://api:5000
            # - MOCKSCRAPE=
        env_file:
            - .env
        depends_on:
            - api
        networks:
            - backend
            - traefik-net

    api:
        build: ./api
        volumes:
            - ./api/api/:/app/app
        environment:
            - DATABASE_URL=postgresql://postgres:example@db/postgres
            - PORT=5000
        restart: always
        depends_on:
            - db
        networks:
            - backend
            - traefik-net

    ui:
        build: ./frontend
        restart: always
        # ports:
        #     - "80:80"
        depends_on:
            - api
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ui.entrypoints=web"
            - "traefik.http.routers.ui.rule=Host(`iracingnotify.live`)"
        networks:
            - traefik-net
            - backend

volumes:
    db-storage:
    iracing-notify-store:

networks:
    traefik-net:
        external: true
    backend:
        external: false
