version: "3.7"

services:
    db:
        image: postgres
        volumes:
            - db-storage:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
        ports:
        - '5432:5432'
        volumes:
        - db-storage:/var/lib/postgresql/data
        restart: unless-stopped

    scraper:
        build: ./scraper
        volumes:
            - iracing-notify-store:/app/data/
            - ./scraper/scraper/:/app/scraper/
        restart: unless-stopped

volumes:
    db-storage:
    iracing-notify-store:
