version: "3.7"

services:
    db:
        image: postgres
        volumes:
            - db-storage:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - "5432:5432"
        restart: unless-stopped

    scraper:
        build: ./scraper
        volumes:
            - iracing-notify-store:/app/data/
            - ./scraper/scraper/:/app/scraper/
        restart: unless-stopped
        depends_on:
            - api

    api:
        build: ./api
        volumes:
            - ./api/api/:/app/api/
        ports:
            - "8000:8000"
        restart: unless-stopped
        depends_on:
            - db

volumes:
    db-storage:
    iracing-notify-store:
