version: "3.1"

services:
    scraper:
        build: ./scraper
        image: scullionw/iracing-notify-scraper

    api:
        build: ./api
        image: scullionw/iracing-notify-api

    ui:
        build: ./frontend
        image: scullionw/iracing-notify-ui