apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-redis
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  labels:
    app: redis
    type: local
spec:
  storageClassName: local-storage-redis
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/redis"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pv-claim
  labels:
    app: redis
spec:
  storageClassName: local-storage-redis
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi