apiVersion: apps/v1
kind: Deployment
metadata:
  name: iracing-notify-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      run: iracing-notify-ui
  template:
    metadata:
      labels:
        run: iracing-notify-ui
    spec:
      containers:
        - name: iracing-notify-ui
          image: scullionw/iracing-notify-ui
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iracing-notify-ui
  labels:
    run: iracing-notify-ui
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    run: iracing-notify-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iracing-notify-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: acme-prod
    traefik.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: "iracingnotify.live"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iracing-notify-ui
                port:
                  number: 80
  tls:
    - hosts:
        - iracingnotify.live
      secretName: iracingnotify-live-tls
