VIP = {
    "f1": [
        "Max Verstappen",
        "Lando Norris",
        "Suellio Almeida",
        "Alexander Albon",
        "Carlos Sainz",
        "Charles Leclerc",
        "Antonio Giovinazzi",
        "George Russell",
        "Fernando Alonso",
        "Mick Schumacher",
        "Nicholas Latifi",
        "Romain Grosjean",
    ],
    "ex_f1": [
        "Stoffel Vandoorne",
        "Robert Kubica",
        "Juan Pablo Montoya",
        "Rubens Barrichello",
        "Jos Verstappen",
    ],
    "real": ["Daniel Juncadella", "Shane van Gisbergen"],
    "iracing_elite": [
        "Maximilian Benecke",
        "Max Benecke",
        "Joshua K Rogers",
        "Chris Lulham",
    ],
    "qc": ["David Sirois", "Guillaume Lévesque"],
    "friends": [
        "Sandy Scullion",
        "Charles Asselin",
        "Emrick Vincent" "Lou-James Scullion",
        "Nicolas Cool",
        "Samuel Asselin2",
        "Kurtis Duddy2",
        "Paul Asselin",
        "Steven Hatcher",
    ],
}
