name: CI to Docker Hub

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push api
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/iracing-notify-api:latest

      - name: Build and push frontend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/iracing-notify-ui:latest

      - name: Build and push scraper
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./scraper
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/iracing-notify-scraper:latest

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
